
name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v3
    - name: Test application
      run: make test
    - name: Build Binary
      run: make all
