name: Lint the code

on: 
  workflow_dispatch:
  push:
    branches:    
      - develop
      - main

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cppcheck
        run: sudo apt-get install cppcheck
      - name: Run Code analysis
        run: cppcheck src/ test/ 2> err.txt
      - name: Check if the linting failed
        run: |
          if [ -s err.txt ]; then
            echo File is not empty
            cat err.txt
            exit 1
          fi
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Check formatting
        run: clang-format --dry-run --Werror src/**/*.c src/*.c include/**/*.h include/*.h test/*.c test/**/*.c -- > err.txt
      - name: Check if the linting failed
        run: |
          if [ -s err.txt ]; then
            echo File is not empty
            cat err.txt
            exit 1
          fi
